name: First work-flow
on: workflow_dispatch

jobs: 
    first__jobs:
        runs-on: ubuntu-latest
        env:
            DOCKER_FILE: adjflajq43tqwt0
        steps:
        - name: welcome message
          run: echo "welcome $DOCKER_FILE"
        - name: checking out the br 
          uses: actions/checkout@v4
        - name: listing the file
          run: ls
        - name: install
          run: npm install
        - name: uploadjobs
          uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: client/index.html

    second__jobs:
        runs-on: ubuntu-latest
        steps:
        - name: welcome second
          run: cat readme.txt
    